project_id = "dsrfakzwbirytxtfxydz"

[functions.create-user]
verify_jwt = false

[functions.manage-user]
verify_jwt = false

[functions.list-users]
verify_jwt = false

[functions.delete-equipment]
verify_jwt = false

[functions.confirm-by-client]
verify_jwt = false

[functions.get-equipment-by-token]
verify_jwt = false

[functions.search-erp-order]
verify_jwt = false

[functions.list-erp-orders]
verify_jwt = false

[functions.update-erp-order-status]
verify_jwt = false

[functions.update-erp-equipment-status]
verify_jwt = false

[functions.gerar-boleto]
verify_jwt = false

[functions.get-erp-boleto-data]
verify_jwt = false

[functions.sync-boletos-status]
verify_jwt = false

[functions.optimize-routes-ai]
verify_jwt = false

[functions.get-erp-analytics]
verify_jwt = false

[functions.get-client-equipment]
verify_jwt = false

[functions.validate-equipment-patrimony]
verify_jwt = false

[functions.ocr-patrimony]
verify_jwt = false
