project_id = "dsrfakzwbirytxtfxydz"

[functions.create-user]
verify_jwt = false

[functions.manage-user]
verify_jwt = false

[functions.list-users]
verify_jwt = false

[functions.delete-equipment]
verify_jwt = false

[functions.confirm-by-client]
verify_jwt = false

[functions.get-equipment-by-token]
verify_jwt = false

[functions.search-erp-order]
verify_jwt = false
